/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JAccjyz35gQ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Navigation } from './navigation';
import Image from 'next/image';
import ContactSvg from '../../public/contact.svg';

export function Landing() {
  return (
    <>
      <Navigation />

      <div
        key="1"
        className="flex flex-col items-center justify-center min-h-[100dvh] max-w-7xl">
        <section className="w-full flex justify-center items-center pt-24 pb-12 md:pb-24 lg:pb-32 xl:pb-48">
          <div className="container px-4 md:px-6 lg:px-16 xl:px-24 w-full">
            <div className="flex flex-col justify-center items-center space-y-6 text-center h-full">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  BVS Satya Manasa
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl">
                  UI/UX Designer with a passion for creating intuitive and
                  visually stunning digital experiences.
                </p>
              </div>
              <div className="flex whitespace-nowrap gap-2  flex-row md:min-h-auto">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                  href="#">
                  View Work
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                  href="#">
                  Get in Touch
                </Link>
              </div>
              <div className="flex items-center gap-4 animate-fade-in">
                <Link
                  className="text-gray-500 hover:text-gray-900 transition-colors duration-300"
                  href="#">
                  <TwitterIcon className="h-6 w-6" />
                  <span className="sr-only">Twitter</span>
                </Link>
                <Link
                  className="text-gray-500 hover:text-gray-900 transition-colors duration-300"
                  href="#">
                  <LinkedinIcon className="h-6 w-6" />
                  <span className="sr-only">LinkedIn</span>
                </Link>
                <Link
                  className="text-gray-500 hover:text-gray-900 transition-colors duration-300"
                  href="#">
                  <InstagramIcon className="h-6 w-6" />
                  <span className="sr-only">Instagram</span>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  My Skills
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  I'm proficient in a variety of design tools and technologies,
                  allowing me to create visually stunning and user-friendly
                  digital experiences.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-2 gap-6 py-12 sm:grid-cols-4 lg:grid-cols-6 animate-fade-in">
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <FigmaIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">Figma</span>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <PencilIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">Sketch</span>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <XIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">Adobe XD</span>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <ImageIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">Photoshop</span>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <PencilIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">Illustrator</span>
              </div>
              <div className="flex flex-col items-center justify-center space-y-2 group">
                <div className="relative h-12 w-12 overflow-hidden rounded-full bg-gray-200 group-hover:scale-110 transition-transform duration-300 ease-in-out">
                  <TextIcon className="absolute top-1/2 left-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                </div>
                <span className="text-sm font-medium">HTML</span>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100"
          id="work">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Featured Work
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  A selection of my best UI/UX design projects, showcasing my
                  attention to detail and ability to create visually stunning
                  and user-friendly digital experiences.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3 animate-fade-in">
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 1"
                  className="mx-auto aspect-video w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-gray-900/80 to-transparent p-6 text-white opacity-0 transition-all duration-300 group-hover:opacity-100">
                  <h3 className="text-xl font-bold">Project 1</h3>
                  <p className="mt-2 text-sm">
                    A sleek and modern e-commerce website design.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 2"
                  className="mx-auto aspect-video w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-gray-900/80 to-transparent p-6 text-white opacity-0 transition-all duration-300 group-hover:opacity-100">
                  <h3 className="text-xl font-bold">Project 2</h3>
                  <p className="mt-2 text-sm">
                    A clean and intuitive mobile app design.
                  </p>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 3"
                  className="mx-auto aspect-video w-full object-cover object-center transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 flex flex-col items-start justify-end bg-gradient-to-t from-gray-900/80 to-transparent p-6 text-white opacity-0 transition-all duration-300 group-hover:opacity-100">
                  <h3 className="text-xl font-bold">Project 3</h3>
                  <p className="mt-2 text-sm">
                    A visually striking and user-friendly website design.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:px-16 xl:px-24 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                About Jane Doe
              </h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Jane Doe is a passionate UI/UX designer with over 5 years of
                experience in creating intuitive and visually stunning digital
                experiences. She has a keen eye for detail and a deep
                understanding of user behavior, which she leverages to design
                products that not only look great but also provide a seamless
                and enjoyable user experience.
              </p>
            </div>
            <img
              alt="Jane Doe"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last lg:aspect-square"
              src="/placeholder.svg"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6 lg:px-16 xl:px-24 flex flex-col items-center space-y-6 mx-auto">
            <div className="text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Get in touch
                </h2>
                <p className=" max-w-[900px] w-full text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Have a question or want to work together? Fill out the form
                  below and we'll get back to you as soon as possible.
                </p>
              </div>
            </div>
            <div className="flex flex-col w-full items-center md:flex-row md:gap-16">
              <div className="w-full max-w-[440px]">
                <form className="flex flex-col space-y-4 items-center md:items-stretch">
                  <div className="w-full">
                    <Label
                      htmlFor="name"
                      className="flex space-x-1 items-center mb-[6px]">
                      <UserIcon className="mr-2 h-5 w-5 text-gray-500" />
                      Name
                    </Label>
                    <Input id="name" placeholder="Your Name" required />
                  </div>
                  <div className="w-full">
                    <Label
                      htmlFor="email"
                      className="flex space-x-1 items-center mb-[6px]">
                      <MailIcon className="mr-2 h-5 w-5 text-gray-500" />
                      Email
                    </Label>
                    <Input
                      id="email"
                      placeholder="example@email.com"
                      required
                      type="email"
                    />
                  </div>
                  <div className="w-full">
                    <Label
                      htmlFor="message"
                      className="flex space-x-1 items-center mb-[6px]">
                      <MessageCircleIcon className="mr-2 h-5 w-5 text-gray-500" />
                      Message
                    </Label>
                    <Textarea
                      id="message"
                      placeholder="Your message..."
                      required
                    />
                  </div>
                  <Button className="w-full" type="submit">
                    <SendIcon className="mr-2 h-5 w-5" />
                    Send Message
                  </Button>
                </form>
              </div>
              <div className="hidden md:block">
                <Image
                  width={220}
                  height={220}
                  className="w-full h-full"
                  src={ContactSvg}
                  alt="Illustration"
                />
              </div>
            </div>
          </div>
        </section>

        <footer className="w-full bg-gray-100 py-6">
          <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 md:flex-row md:px-6">
            <p className="text-sm text-gray-500">
              © {new Date().getFullYear()} BVS Satya Manasa. All rights
              reserved.
            </p>

            <nav className="flex gap-4 sm:gap-6">
              <Link
                className="text-sm hover:underline underline-offset-4 text-gray-500"
                href="#">
                Privacy Policy
              </Link>
              <Link
                className="text-sm hover:underline underline-offset-4 text-gray-500"
                href="#">
                Terms of Service
              </Link>
            </nav>
          </div>
        </footer>
      </div>
    </>
  );
}

function FigmaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  );
}

function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  );
}

function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function MessageCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  );
}

function PencilIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  );
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}

function TextIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
